
#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Builds the TerraformCloud PowerShell module from source.

.DESCRIPTION
    This script builds the TerraformCloud module by:
    1. Cleaning the Output directory
    2. Compiling individual function files from src/ into a single .psm1
    3. Generating the module manifest (.psd1) with exported functions
    4. Copying supporting files
    5. Running tests (optional)

.PARAMETER SkipTests
    Skip running tests after building the module.

.PARAMETER Clean
    Only clean the Output directory without building.

.EXAMPLE
    ./Build-Module.ps1
    Builds the module and runs tests.

.EXAMPLE
    ./Build-Module.ps1 -SkipTests
    Builds the module without running tests.

.EXAMPLE
    ./Build-Module.ps1 -Clean
    Only cleans the Output directory.
#>

[CmdletBinding()]
param(
    [switch]$SkipTests,
    [switch]$Clean
)

$ErrorActionPreference = 'Stop'

# Define paths
$RootPath = $PSScriptRoot
$SourcePath = Join-Path $RootPath 'src'
$OutputPath = Join-Path $RootPath 'Output'
$ModulePath = Join-Path $OutputPath 'TerraformCloud'
$TestsPath = Join-Path $RootPath 'Tests'

Write-Host "`n=== TerraformCloud Module Build Script ===" -ForegroundColor Cyan
Write-Host "Root Path: $RootPath" -ForegroundColor Gray

# Clean Output directory
Write-Host "`n[1/4] Cleaning Output directory..." -ForegroundColor Yellow
if (Test-Path $OutputPath) {
    Remove-Item -Path $OutputPath -Recurse -Force
    Write-Host "  ✓ Removed existing Output directory" -ForegroundColor Green
}

if ($Clean) {
    Write-Host "`n✓ Clean complete!" -ForegroundColor Green
    return
}

# Create Output directory structure
Write-Host "`n[2/4] Creating module directory structure..." -ForegroundColor Yellow
New-Item -Path $ModulePath -ItemType Directory -Force | Out-Null
Write-Host "  ✓ Created: $ModulePath" -ForegroundColor Green

# Compile module from source
Write-Host "`n[3/7] Compiling module from source files..." -ForegroundColor Yellow

# Get all function files
$privateFiles = Get-ChildItem -Path (Join-Path $SourcePath 'Private') -Filter '*.ps1' -Recurse -ErrorAction SilentlyContinue
$publicFiles = Get-ChildItem -Path (Join-Path $SourcePath 'Public') -Filter '*.ps1' -Recurse -ErrorAction SilentlyContinue

Write-Host "  Found $($privateFiles.Count) private functions" -ForegroundColor Gray
Write-Host "  Found $($publicFiles.Count) public functions" -ForegroundColor Gray

# Build the combined module file
$moduleContent = @"
# TerraformCloud PowerShell Module
# Auto-generated on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Do not edit this file directly - edit source files in src/ and rebuild

#region Module Variables
# Initialize module-level variables for API connection
`$script:TfcApiBaseUri = 'https://app.terraform.io/api/v2'
`$script:TfcToken = `$null
`$script:TfcHeaders = @{
    'Content-Type' = 'application/vnd.api+json'
}
#endregion Module Variables

#region Private Functions

"@

# Add private functions
foreach ($file in $privateFiles) {
    Write-Verbose "  Adding private function: $($file.Name)"
    $moduleContent += "`n# Source: $($file.FullName.Replace($RootPath, ''))`n"
    $moduleContent += Get-Content -Path $file.FullName -Raw
    $moduleContent += "`n"
}

$moduleContent += @"

#endregion Private Functions

#region Public Functions

"@

# Add public functions and track function names
$exportedFunctions = @()
foreach ($file in $publicFiles) {
    Write-Verbose "  Adding public function: $($file.Name)"
    $moduleContent += "`n# Source: $($file.FullName.Replace($RootPath, ''))`n"
    $content = Get-Content -Path $file.FullName -Raw
    $moduleContent += $content
    $moduleContent += "`n"

    # Extract function name from file content
    if ($content -match 'function\s+([\w-]+)') {
        $exportedFunctions += $Matches[1]
    }
}

$moduleContent += @"

#endregion Public Functions

"@

# Write the compiled module file
$compiledModuleFile = Join-Path $ModulePath 'TerraformCloud.psm1'
# UTF-8 with BOM — PSScriptAnalyzer flags PSUseBOMForUnicodeEncodedFile
# on non-ASCII content without a BOM, and PowerShell 5.1 requires the BOM
# to detect UTF-8 correctly when loading the module.
[System.IO.File]::WriteAllText(
    $compiledModuleFile,
    $moduleContent,
    [System.Text.UTF8Encoding]::new($true)
)
Write-Host "  ✓ Compiled module: TerraformCloud.psm1" -ForegroundColor Green
Write-Host "    Total functions: $($exportedFunctions.Count)" -ForegroundColor Gray

# Generate module manifest
Write-Host "`n[4/7] Generating module manifest..." -ForegroundColor Yellow

$manifestPath = Join-Path $ModulePath 'TerraformCloud.psd1'
$manifestParams = @{
    Path              = $manifestPath
    RootModule        = 'TerraformCloud.psm1'
    ModuleVersion     = '1.4.1' # x-release-please-version
    Author            = 'Seth T. Bacon'
    Description       = 'PowerShell module for HCP Terraform (Terraform Cloud/Enterprise) API'
    PowerShellVersion = '7.0'
    FunctionsToExport = $exportedFunctions
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    Tags              = @('Terraform', 'TerraformCloud', 'HCP', 'IaC', 'Infrastructure', 'API', 'Automation', 'HashiCorp')
    LicenseUri        = 'https://github.com/sethbacon/hcp-terraform-pwsh/blob/main/LICENSE'
    ProjectUri        = 'https://github.com/sethbacon/hcp-terraform-pwsh'
    ReleaseNotes      = 'See https://github.com/sethbacon/hcp-terraform-pwsh/blob/main/CHANGELOG.md'
}

New-ModuleManifest @manifestParams
Write-Host "  ✓ Generated manifest with $($exportedFunctions.Count) exported functions" -ForegroundColor Green

# Copy supporting files
Write-Host "`n[5/7] Copying supporting files..." -ForegroundColor Yellow

$readmeFile = Join-Path $RootPath 'README.md'
if (Test-Path $readmeFile) {
    Copy-Item -Path $readmeFile -Destination $ModulePath -Force
    Write-Host "  ✓ Copied: README.md" -ForegroundColor Green
}

$licenseFile = Join-Path $RootPath 'LICENSE'
if (Test-Path $licenseFile) {
    Copy-Item -Path $licenseFile -Destination $ModulePath -Force
    Write-Host "  ✓ Copied: LICENSE" -ForegroundColor Green
}

# Verify build
Write-Host "`n[6/7] Verifying build..." -ForegroundColor Yellow

try {
    $manifest = Test-ModuleManifest -Path (Join-Path $ModulePath 'TerraformCloud.psd1') -ErrorAction Stop -WarningAction SilentlyContinue
    Write-Host "  ✓ Module manifest is valid" -ForegroundColor Green
    Write-Host "    Name: $($manifest.Name)" -ForegroundColor Gray
    Write-Host "    Version: $($manifest.Version)" -ForegroundColor Gray
    Write-Host "    Author: $($manifest.Author)" -ForegroundColor Gray
    Write-Host "    Exported Functions: $($manifest.ExportedFunctions.Count)" -ForegroundColor Gray
} catch {
    Write-Host "  ✗ Module manifest validation failed: $_" -ForegroundColor Red
    throw
}

# Import module to verify it loads
try {
    Import-Module (Join-Path $ModulePath 'TerraformCloud.psd1') -Force -ErrorAction Stop
    Write-Host "  ✓ Module imports successfully" -ForegroundColor Green

    $loadedModule = Get-Module TerraformCloud
    Write-Host "    Loaded Commands: $($loadedModule.ExportedCommands.Count)" -ForegroundColor Gray

    Remove-Module TerraformCloud -Force
} catch {
    Write-Host "  ✗ Module import failed: $_" -ForegroundColor Red
    throw
}Write-Host "`n✓ Build complete!" -ForegroundColor Green
Write-Host "Module location: $ModulePath" -ForegroundColor Cyan

# Run tests if requested
if (-not $SkipTests) {
    Write-Host "`n[7/7] Running Tests..." -ForegroundColor Cyan

    # Check if Pester is available
    $pesterModule = Get-Module -Name Pester -ListAvailable | Where-Object { $_.Version -ge '5.0' }
    if (-not $pesterModule) {
        Write-Host "  ⚠ Pester 5.0+ not found. Skipping tests." -ForegroundColor Yellow
        Write-Host "    Install with: Install-Module -Name Pester -Force -SkipPublisherCheck" -ForegroundColor Gray
    } else {
        Write-Host "  Running unit tests..." -ForegroundColor Yellow

        try {
            Import-Module Pester -MinimumVersion 5.0 -ErrorAction Stop

            $config = New-PesterConfiguration
            $config.Run.Path = Join-Path $TestsPath 'Unit'
            $config.Output.Verbosity = 'Normal'
            $config.Run.PassThru = $true

            $result = Invoke-Pester -Configuration $config

            if ($result.FailedCount -eq 0) {
                Write-Host "`n  ✓ All tests passed! ($($result.PassedCount)/$($result.TotalCount))" -ForegroundColor Green
            } else {
                Write-Host "`n  ✗ Some tests failed! ($($result.FailedCount)/$($result.TotalCount) failures)" -ForegroundColor Red
                throw "Test failures detected"
            }
        } catch {
            Write-Host "  ✗ Test execution failed: $_" -ForegroundColor Red
            throw
        }
    }
} else {
    Write-Host "`n[7/7] Skipping tests (use without -SkipTests to run)" -ForegroundColor Yellow
}Write-Host "`n=== Build Summary ===" -ForegroundColor Cyan
Write-Host "Status: Success" -ForegroundColor Green
Write-Host "Output: $ModulePath" -ForegroundColor Gray
Write-Host "`nTo import the module, run:" -ForegroundColor Gray
Write-Host "  Import-Module '$ModulePath/TerraformCloud.psd1'" -ForegroundColor White
Write-Host ""
